name: build rule set

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: go run -v .
      
      - name: Build
        run: bash ./build-adguard.sh
      
      - name: Release
        run: bash .github/release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          